### ISSUE TITLE
Artifacts aren't working

### ISSUE THREAD

**Issue by Mastrmyrtr9** [tetraminus/RiskOfRelics#19]
I unlocked a few artifacts, everything worked fine. Once I unlocked roughly 5, they started bugging out. I can't disable the ones I've previously used, but I can freely enable/disable the ones I've been using. The artifact which replaces enemies with a boss every 10 floors also is treating every floor as a boss, and therefore not giving me any rewards. It also has the lock icon over it on the artifact screen, preventing me from turning it off.

If more information is required I can provide it. I really enjoy this mod and it sucks to have to disable it just to play the game again.

**Comment by tetraminus** [comment]
can you upload the contents of the config file?
on windows it should be in %APPDATA%\local\ModTheSpire\RiskOfRelicsMod\

**Comment by Mastrmyrtr9** [comment]
It's a .properties file, which is an unsupported file type for Github. Should I change it to something?

**Comment by tetraminus** [comment]
it should just be a .txt file with a different name, so you should be able to change it to .txt, and just ctrl c ctrl v the contents here.

**Comment by Mastrmyrtr9** [comment]
[riskOfRelicsConfig.txt](https://github.com/tetraminus/RiskOfRelics/files/12243851/riskOfRelicsConfig.txt)

Okay, I think that's it

**Comment by tetraminus** [comment]
FOUND IT, ITS FIXIN' TIME

**Comment by tetraminus** [comment]
Update pushed. Thanks for the report!
