### ISSUE TITLE
Dying to Heart while unlocking an Artifact permanently enabled that Artifact and also did not unlock it

### ISSUE THREAD

**Issue by AndrewKoons** [tetraminus/RiskOfRelics#27]
**Describe the bug**
Died to the Heart while trying to unlock Artifact of Command enabled Artifact of Command on every subsequent run without the option to disable it - until I beat the Heart again to unlock it.

**To Reproduce**
1. Go to Bulwark's Ambry
2. Select Artifact of Command
3. Die to the Heart
4. Artifact of Command is enabled and locked

Reproduced with Artifact of Chaos to confirm. Going through the game again to Bulwark's Ambry, selecting the artifact again, and beating the heart unlocks the artifact and makes it toggleable.

**Expected behavior**
Expected that the Artifact of Command would either remain locked and be disabled or would be unlocked and able to be toggled.

**Screenshots**
Image below shows the issue with Artifact of Chaos.
![image](https://github.com/tetraminus/RiskOfRelics/assets/3445865/63ec1f3d-79bd-4f0b-9e3e-30dcb7863812)

**Additional context**

Mods enabled: Risk of Relics, Reliquary, BaseMod, StsLib

**Comment by tetraminus** [comment]
you may be on an older version of the mod, as this was fixed a few versions ago. if you compiled from the main branch, that is a bit outdated and may not include the fix. the latest version is 2.2.0, check in MTS if it's the same version

**Comment by AndrewKoons** [comment]
Augh, sorry about that. Updated, and it resolved on the next run. Thank you!
