### ISSUE TITLE
Egocentrism consuming the Artifact Key skips the Heart Fight

### ISSUE THREAD

**Issue by AndrewKoons** [tetraminus/RiskOfRelics#28]
**Describe the bug**
Made it past Bulwark's Ambry with just Egocentrism and the Artifact Key. After the elite fight, Egocentrism consumed Artifact Key. The heart fight led to a black screen. On reloading the game, got the end game screen for after the heart fight.

**To Reproduce**
1. Go to Bulwark's Ambry, with just Egocentrism and the Artifact Key. At the time Egocentrism had a count of about 15 if I recall correctly.
2. Select an Artifact (I did artifact of Command)
3. Proceed to the elite fight. At the end of that fight, egocentrism will eat the Artifact Key.
4. Select the Heart Fight. You should get a black screen that does not allow interaction.
5. Restart the game and pick up where you left off. The end game screen with pictures showing the character defeating the heart should show, and then the end game score screen.

**Expected behavior**
Expected to be able to continue with the heart fight as normal.

**Screenshots**

**Additional context**
Also worth noting that I was also experiencing another bug at the time, wherein Artifact of Command was permanently enabled, but was still locked. The heart fight did not occur, but the artifact unlocked as though the game had been completed with that.

I was playing as Watcher. Due to the RNG involved, I have not been able to reproduce it on demand.

Mods enabled: 
BaseMod, Risk of Relics, StSLib, Reliquary

**Comment by tetraminus** [comment]
fixed, update will be pushed soon

**Comment by tetraminus** [comment]
uploaded
