### ISSUE TITLE
Essence of Heresy Text Clarification

### ISSUE THREAD

**Issue by AndrewKoons** [tetraminus/RiskOfRelics#29]
**Describe the bug**
Essence of Heresy states "When you deal unblocked damage, apply 5 ruin to the enemy", but should specify "unblocked attack damage" or similar, or else should trigger on lightning orb passive, for example.

**To Reproduce**
1. With Defect, acquire Essence of Heresy
2. In combat, channel 1 lightning
3. End turn.
4. When lightning orb triggers, no stacks of Ruin are applied.

**Expected behavior**
Expected that either the text specifies attack damage, or Ruin is applied on any kind of damage. Preferably the latter, as it seemed fun when I picked it, but whatever was intended.

**Screenshots**
![image](https://github.com/tetraminus/RiskOfRelics/assets/3445865/c12fb6b9-d29c-48f9-a4fa-d1ec1376324e)

**Additional context**
Four mods installed: BaseMod, Risk of Relics, StSLib, Reliquary

There are other cards with similar ambiguity, like Kjaro's band, which I see also triggers on attack, but the text says "hit". For something like Envenom, the game specifies "Whenever an Attack deals unblocked damage"

**Comment by tetraminus** [comment]
uploaded
