### ISSUE TITLE
3D Printed Backup Mag does not give additional relic

### ISSUE THREAD

**Issue by AndrewKoons** [tetraminus/RiskOfRelics#31]
**Describe the bug**
Used a 3D Printer to obtain a backup magazine, but no copy of an existing relic came with it.

**To Reproduce**
1. Go to backup mag 3D Printer without appropriate scrap. (I had 1 rare scrap at the time)
2. Click to sacrifice a relic (in this case, porcupine quills from Reliquary)
3. Backup mag is obtained without additional other relic that it should provide.

**Expected behavior**
Should obtain backup mag and a copy of a relic that is already owned.

**Screenshots**
![image](https://github.com/tetraminus/RiskOfRelics/assets/3445865/8979edd2-6191-4535-a37a-d7b0202fcbb5)

**Additional context**
Mods installed: BaseMod, StsLib, Reliquary, Risk of Relics

Love the mod, I'm a big fan.

**Comment by tetraminus** [comment]
got it! thanks for the report.
