### ISSUE TITLE
Glowing shard does not damage the Bulwarks Ambry when played with Gesture of the Drowned

### ISSUE THREAD

**Issue by Cameron-Roth** [tetraminus/RiskOfRelics#32]
**Describe the bug**
During the Bulwark's ambry fight (riskOfRelics:BulwarksAmbry) a character with the Gesture of the Drowed relic (riskOfRelics:Gesture) cannot damage the ambry with the Glowing Shard card (riskOfRelics:GlowingShard). The relic will attempt to play the card and do no damage, immediately moving it to the discard pile.

**To Reproduce**
Preferably setup a deck capable of defeating the first of the Bulwark's summons. I grabbed two Dropkicks and a thunderwave foran easy infinite.

Run these commands in the dev console
relic add riskOfRelics:Gesture
fight riskOfRelics:BulwarksAmbry

Defeat the first set of sentries and try to play the glowing shard card.

**Expected behavior**
Gesture automatically plays the glowing shard card and does damage to the Ambry

**Additional context**
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - stslib (2.10.1)
 - RiskOfRelics (2.2.6)

**Comment by tetraminus** [comment]
fixed, I'll push out an update soon
