### ISSUE TITLE
Bulwark Shard Relic replaced by Artifact glitches the Act IV boss fight.

### ISSUE THREAD

**Issue by AndrewKoons** [tetraminus/RiskOfRelics#33]
**Describe the bug**
Final fight skips after picking up artifact which replaces all relics, and the relic to access Bulwark's Ambry is replaced.

**To Reproduce**
1. Go to Bulwark's Ambry
2. Select the artifact which replaces all relics every few floors (the name escapes me atm)
3. Do the elite fight, and have all the relics replaced.
4. The final fight will be unselectable. If you save and quit the game, and reload, you will get the ending screen as though you had beaten the boss fight in act IV, and it will say "No artifacts selected".

**Expected behavior**
Expected that we would either be able to proceed with the Bulwark's Ambry fight, as Act IV has already been transformed, or it would be replaced with the standard Act IV heart fight.

**Screenshots**
Could not get a screenshot, unfortunately.

**Additional context**
Seems very similar to the bug where the relic was deleted by Egocentrism.

**Comment by tetraminus** [comment]
The fix will be pushed soon. Thanks for the report!
