### ISSUE TITLE
igniton tank negates dissarm

### ISSUE THREAD

**Issue by evolvedtacos** [tetraminus/RiskOfRelics#34]
**Describe the bug**
when i use disarm, ignition tank adds 2 strength to the enemies negating the debuff

*To Reproduce**
1. have ignition tank
2. use disarm
3. See error

**Expected behavior**
i expected the enemy to lose 4 strength.

**Screenshots**
![image](https://github.com/tetraminus/RiskOfRelics/assets/155578794/518f385c-dd0b-4efa-848d-57bf30e742ee)
![image](https://github.com/tetraminus/RiskOfRelics/assets/155578794/c94eae14-4669-4fb9-a43a-ea8a9db65ee8)

**Additional context**
i am playing on ascension 1, so the sentry do 9 damage base. it is also of note that the strength description is also wrong.

**Comment by tetraminus** [comment]
Released a fix!
