### ISSUE TITLE
Crash if Bulwark's Ambry Runs out of space to spawn enemies

### ISSUE THREAD

**Issue by mtjohnson47** [tetraminus/RiskOfRelics#38]
**Describe the bug**
I was playing a fairly slow deck built around duplicating powers and building up poison/modded poison, so I wasn't really killing the elites quick enough.  When there were 3 of the spire spear/shield, the Ambry tried spawning another pair, which fully locked up not just the game, but the monitor the game was running on.

**To Reproduce**
1. Go to Bulwark's Ambry
2. Don't kill the elites
3. If that doesn't cause the crash, kill the elites, but don't kill the Act 4 elites.
4. If that doesn't cause the crash, kill only one of them.
5. If that doesn't work, then use the attached save file and mod list, play it until you have 4 of the act 4 elites, and then don't kill them.  I'm afraid I don't remember the exact order I played cards in.

**Expected behavior**
The Ambry should just not spawn more elites if it can't, or maybe add a queuing system to spawn extra elites as soon as one dies.

**Screenshots**
![image](https://github.com/tetraminus/RiskOfRelics/assets/5100948/b5233bca-6906-4ccc-a157-892a7839c0a0)
A few hundred or thousand lines above this was a java.lang.StackOverflowError.

**Additional context**
Windows 10, STS V2.3.4
Mod List
AKDream's More Relics 1.5.1
BaseMod 5.53.2
Bossy Relics 0.9.2
Chimera Cards 1.0.2
Hug You Relics 1.2.42
More Stackable Relics 2.4.4
One Hundred Relics 1.0.0
Relic Stats 1.2.2
Risk of Relics 2.3.6
StSLib 2.11.0
Stackable Relics 1.3.6
Terraria Relics 0.1.1
Shop Mod 1.1.2
Spire Biomes 1.3.0
Aspiration 1.9.5
Bundle of Bundles 5.4.2
Bundle of Content 1.6.2
Bundle of Food 2.1.6
Card Mastery 1.0.1
Energized Spire 1.16.0
Ram Saver 0.2.1
Reliquary 0.5.3

I checked the mts_process_launch.log, then made the mistake of opening the game to get the version numbers, which reset the log.  I've attached the SlayTheSpire.log, but it ends before the crash.  I think the only thing missing is the crash message, which is pretty well represented by the screenshot.

I tried replaying the game to generate a new log, but I beat the Ambry and realized 2 seconds later, "Wait, I was supposed to be not killing it for the crash log."  I've attached the .run file in case it helps.

[SlayTheSpire_202401290455_1.log.zip](https://github.com/tetraminus/RiskOfRelics/files/14080806/SlayTheSpire_202401290455_1.log.zip)
[1706511705.zip](https://github.com/tetraminus/RiskOfRelics/files/14080803/1706511705.zip)

**Comment by tetraminus** [comment]
Rats, I thought I had fixed this a while ago. I'll see what I can do.

**Comment by tetraminus** [comment]
should be actually fixed now? Thanks for the report!
