### ISSUE TITLE
Downfall act 4 with Artifact key

### ISSUE THREAD

**Issue by skilledHuntr** [tetraminus/RiskOfRelics#40]
**Describe the bug**
I am unable to pick my starting room in act 4 essentially making me unable to continue.
**To Reproduce**
1. Download Downfall (plus maybe other mods? I have a large amount installed but I think this bug is because of the artifact key)
2. Buy Artifact key
3. Go to act 4
5. See the error.

**Expected behavior**
You cannot pick your starting room.

**Screenshots**
![Skærmbillede (201)](https://github.com/tetraminus/RiskOfRelics/assets/160400733/84c50186-8831-4a36-806f-ef5aa2ffde1d)

**Additional context**
I filed a report to the creators of downfall and they stated that the bug was happening due to downfall not being able to properly flip the map with the question mark that the artifact key provides.

**Comment by tetraminus** [comment]
What version of risk of relics do you have?  I've tried to fix this at least 3 times now. I am marking this as a known incompatibility if you're on the latest version, but the newest version should have fixed this. otherwise, to continue that run you should use Basemod's debug command.

**Comment by tetraminus** [comment]
Yeah, I tested it it doesnt work. I'm just banning the yellow key from downfall runs. i might come back to this in the future.
