### ISSUE TITLE
Essence of Heresy can be triggered multiple times

### ISSUE THREAD

**Issue by DaPiFanatic** [tetraminus/RiskOfRelics#43]
The boss relic "Essence of Heresy", that says "At the start of each combat lose 4 strength. When you deal unblocked damage, apple 6 Ruin to the enemy. Right click this relic to trigger all Ruin effects." can be triggered multiple times by right clicking it multiple times

1. Obtain relic
2. Do unblocked combat damage
3. Spam right click on the relic
4. Does damage multiple times before removing stacks of Ruin

**Comment by DaPiFanatic** [comment]
Update: someone in the discord suggested opening the menu and right clicking the relic multiple times, have confirmed that this triggers the relic every time you click so this just gives theoretically infinite damage

**Comment by tetraminus** [comment]
Patched! thanks for the report.
