### ISSUE TITLE
Add an isObtained check to BisonSteak's update code

### ISSUE THREAD

**Issue by qw2341** [tetraminus/RiskOfRelics#44]
**Describe the bug**
Bison steak will grant max hp up no matter obtained or not.

**To Reproduce**
Call Bison Steak's update method when player hasn't obtained it yet, i.e., when using the relic picking screen in my mod, Loadout

**Expected behavior**
It should not add health until obtained.

**Screenshots**

**Additional context**
using RelicGet hook from BaseMod and onEquip() call to account for relics before BisonSteak might be better, imo

**Comment by tetraminus** [comment]
Got it, will fix.

Bison steak was originally done with relicget, but for some reason that hook is... Jank? to say the least. this seems to be generally more stable, at least until something like this happens.

**Comment by tetraminus** [comment]
Uploaded!
